project1/project1/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projectapp.urls'))
]

project1/projectapp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from . import views 
from django.urls import path

app_name = 'projectapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movies/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),  
    path('delete/<int:id>/', views.delete, name='delete'),  
   
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/projectapp/models.py
from django.db import models

class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img=models.ImageField(upload_to='photo')

    def __str__(self):
        return self.name

project1/projectapp/views.py
from django.shortcuts import render, redirect
from .form import MovieForm  # Make sure your forms module is named correctly
from .models import Movie

def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)

def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})

def add_movie(request):
    if request.method == "POST":
        Name = request.POST.get('name',)
        Desc = request.POST.get('desc',)
        Year = request.POST.get('year',)
        Img = request.FILES['img']
        movie = Movie(name=Name, desc=Desc, year=Year, img=Img)
        movie.save()
    return render(request, 'add.html')

def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES or None, instance=movie)  # Corrected this line
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

project1/projectapp/templates/add.html
{% extends 'baase.html' %}

{% block body %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">Add New Movie</h2>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Movie Name:</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter your movie name">
            </div>
            <div class="form-group">
              <label for="desc">Description:</label>
              <input type="text" class="form-control" id="desc" name="desc" placeholder="About it">
            </div>
            <div class="form-group">
              <label for="year">Year:</label>
              <input type="number" class="form-control" id="year" name="year">
            </div>
            <div class="form-group">
              <label for="img">Image:</label>
              <input type="file" class="form-control-file" id="img" name="img">
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-4">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

project1/projectapp/templates/baase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bgstyle1.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project1/projectapp/templates/delete.html
{% extends 'baase.html' %}

{% block body %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">Delete Movie</h2>
          <form method="POST">
            {% csrf_token %}
            <p class="text-center mb-4">Are you sure you want to delete this movie?</p>
            <div class="text-center">
              <button type="submit" class="btn btn-danger">Yes, Delete</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

project1/projectapp/templates/detail.html
{% extends 'baase.html' %}
{% block body %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        h4,h5,h6{
        color:white;
        }
    </style>
</head>
<body>
<div class="container mt-5">
    <div class="row">
        <div class="col md-6">
          <img src="{{movie.img.url}}" width="600" height="600">
        </div>
    <div class="col md-5">
       <h4>{{movie.name}}</h4>
        <h5>{{movie.desc}}</h5>
        <h6>{{movie.year}}</h6>
        <a class="btn btn-warning" href="{% url 'projectapp:update' movie.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'projectapp:delete' movie.id %}">delete</a>
    </div>

    </div>
</div>
</body>
</html>

{% endblock %}

project1/projectapp/templates/edit.html
{% extends 'baase.html' %}

{% block body %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">Update</h2>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block mt-4">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

project1/projectapp/templates/index.html
{% extends 'baase.html' %}
{% block body %}

<div class="container mt-5">
    <div class="row justify-content-center">
        {% for i in movie_list %}
        <div class="col-md-4 mb-4">
            <div class="card text-center" style="width: 20rem; height:580px">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="300px">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <h6 class="card-text">{{i.year}}<h6>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'projectapp:detail' i.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'projectapp:add_movie'%}" class="btn btn-primary">add</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>




    {% endblock %}
</a>